- job_name: 'snmp_fontes'
  scrape_interval: 60s
  scrape_timeout: 60s
  static_configs:
    - targets:
      - 10.0.0.1  #IP da fonte a ser monitorada
      - 10.0.0.2  #IP da fonte a ser monitorada
  metrics_path: /snmp
  params:
    module: [fonte_phb]
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: host
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: snmp-exporter:9000
